server:
  port: 8090
spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
  application:
    name: medilaboGateway
  cloud:
    gateway:
      routes:
        - id: patientService
          uri: http://localhost:8091
          predicates:
            - Path=/api/patient/**
        - id: noteService
          uri: http://localhost:8093
          predicates:
            - Path=/api/note/**
        - id: resultService
          uri: http://localhost:8094
          predicates:
            - Path=/api/result/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        security: DEBUG

jwt:
  expirationMs: "1000000"
