version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: medilaboservice
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: patientNote
    container_name: mongodb_container
    volumes:
      - mongo_data:/data/db
      - ./mongo-initdb:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  medilabo:
    build:
      context: ../medilabo
      dockerfile: docker/Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - mysql

  medilabo-front:
    build:
      context: ../medilabofront
      dockerfile: docker/Dockerfile
    ports:
      - "8092:8092"

  medilabo-gateway:
    build:
      context: ../medilaboGateway
      dockerfile: docker/Dockerfile
    ports:
      - "8090:8090"

  medilabo-note:
    build:
      context: ../medilaboNote
      dockerfile: docker/Dockerfile
    ports:
      - "8093:8093"

  medilabo-result:
    build:
      context: ../medilaboResult
      dockerfile: docker/Dockerfile
    ports:
      - "8094:8094"

volumes:
  mongoExpress:
  mysql_data:
  mongo_data:
