SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE app_user RESTART IDENTITY;
TRUNCATE TABLE patient RESTART IDENTITY;
SET REFERENTIAL_INTEGRITY TRUE;
INSERT INTO user_access (user_name, user_role) VALUES ('admin', 'admin');
